version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/gitTest
#todo: Add in hooks to test running builds
#hooks:
#  AfterInstall:
#   - location: scripts/install_app_dependencies
#     timeout: 300
#     runas: root
#  ApplicationStart:
#   - location: scripts/start_server
#     timeout: 300
#     runas: root
